 export const mentalHealthKeywords =[ "hello", "hi","hey",
    "depression", "anxiety", "bipolar disorder", "schizophrenia", "OCD",
    "PTSD", "eating disorders", "borderline personality disorder", "GAD", 
    "social anxiety", "sadness", "irritability", "fatigue", "insomnia", 
    "panic attacks", "emotional numbness", "mood swings", "apprehension", 
    "loss of appetite", "excessive worrying", "CBT", "psychotherapy", 
    "medication", "mindfulness", "stress management", "psychodynamic therapy", 
    "DBT", "exposure therapy", "IPT", "art therapy", "meditation", "journaling", 
    "relaxation techniques", "breathing exercises", "yoga", "self-care", 
    "emotional regulation", "cognitive restructuring", "behavioral activation", 
    "support groups", "psychologist", "psychiatrist", "therapist", "counselor", 
    "social worker", "clinical psychologist", "mental health nurse", 
    "psychiatric nurse practitioner", "marriage and family therapist", 
    "substance abuse counselor", "resilience", "coping mechanisms", 
    "stress relief", "well-being", "trauma", "grief", "mental illness", 
    "recovery", "support system", "self-esteem", "diagnosis", "prognosis", 
    "treatment plan", "risk factors", "symptomatology", "clinical intervention", 
    "case management", "assessment", "behavioral health", "mental health crisis", 
    "antidepressants", "anti-anxiety medications", "mood stabilizers", 
    "antipsychotics", "sleep aids", "stimulants", "psychotropic drugs", 
    "herbal supplements", "ECT", "TMS", "stigma", "support networks", 
    "family dynamics", "social isolation", "economic stress", "work-life balance", 
    "community resources", "cultural factors", "life transitions", 
    "relationship issues", "awareness campaigns", "mental health literacy", 
    "early intervention", "public health initiatives", "educational programs", 
    "self-help resources", "wellness workshops", "coping strategies", 
    "resilience training", "mental health advocacy", "psychosis", 
    "neurotic disorders", "psychotic disorders", "somatic disorders", 
    "substance use disorders", "delusional disorder", "acute stress disorder", 
    "schizoaffective disorder", "paranoid personality disorder", 
    "avoidant personality disorder", "narcissistic personality disorder", 
    "histrionic personality disorder", "dependent personality disorder", 
    "antisocial personality disorder", "hysteria", "neurosis", "psychopathy", 
    "self-harm", "suicidal ideation", "trauma-informed care", 
    "grief counseling", "bereavement", "life coaching", "personal development", 
    "emotional intelligence", "stress reduction", "anger management", 
    "mind-body connection", "therapeutic alliance", "peer support", 
    "psychosocial interventions", "family therapy", "group therapy", 
    "individual therapy", "counseling psychology", "clinical supervision", 
    "self-compassion", "compulsive behavior", "obsessions", "compulsions", 
    "psychosomatic symptoms", "psychological trauma", "mental health stigma", 
    "emotional support", "mental health evaluation", "substance abuse treatment", 
    "relapse prevention", "crisis intervention", "positive psychology", 
    "wellness coaching", "mental wellness", "emotional disturbances", 
    "social support", "mental health recovery", "psychoeducation", 
    "emergency mental health services", "addiction counseling", 
    "functional impairment", "quality of life", "behavioral therapy", 
    "relational therapy", "integrative therapy", "trauma recovery", 
    "stress management techniques", "therapeutic interventions", 
    "emotional well-being", "psychosocial support", "mindfulness-based stress reduction", 
    "mindfulness-based cognitive therapy", "cognitive therapy", "behavior modification", 
    "psychological assessment", "therapeutic techniques", "behavioral interventions", 
    "mental health research", "psychological evaluation", "clinical psychology", 
    "mental health screening", "medication management", "self-improvement", 
    "personal growth", "therapeutic exercises", "mental health services", 
    "psychological health", "life skills training", "adaptive coping strategies", 
    "community mental health", "holistic therapy", "mental health advocacy", 
    "behavioral health interventions", "emotional support systems", 
    "psychological counseling", "therapeutic practices", "behavioral psychology", 
    "mental health professionals", "therapy sessions", "psychiatric assessment", 
    "mental health promotion", "clinical practice", "psychoanalytic therapy", 
    "dialectical behavior therapy", "resilience building", "stress management programs", 
    "emotional support groups", "psychotherapy techniques", "cognitive-behavioral techniques", 
    "self-care practices", "mental health awareness", "psychiatric evaluation", 
    "therapeutic modalities", "mental health challenges", "emotional health", 
    "psychosocial interventions", "psychological distress", "mental health management", 
    "cognitive-behavioral interventions", "psychological support", "mental well-being", 
    "mental health issues", "self-help strategies", "wellness strategies", 
    "mental health care", "psychological care", "therapeutic support", 
    "clinical mental health", "psychological interventions", "mental health treatment", 
    "personal therapy", "emotional recovery", "psychiatric treatment", 
    "mental health resources", "psychological therapies", "therapeutic resources", 
    "mental health education", "behavioral health services", "emotional management", 
    "mental health support", "psychological resources", "personal mental health", 
    "therapeutic care", "clinical support", "psychosocial support services", 
    "self-help programs", "mental health counseling", "therapeutic interventions", 
    "psychological wellness", "mental health tools", "wellness resources", 
    "psychosocial services", "mental health issues", "therapeutic techniques", 
    "psychiatric services", "behavioral support", "emotional stability", 
    "mental health practices", "psychiatric care", "therapeutic environments", 
    "mental health recovery", "psychological support services", "mental health strategies", 
    "therapeutic approaches", "mental health disciplines", "psychological strategies", 
    "mental health techniques", "self-care techniques", "emotional resilience", 
    "psychological well-being", "mental health programs", "psychological practices", 
    "wellness interventions", "emotional strategies", "mental health management strategies", 
    "therapeutic interventions", "mental health guidance", "psychological assessment tools", 
    "emotional therapy", "mental health plans", "behavioral health management", 
    "psychosocial support programs", "clinical interventions", "emotional interventions", 
    "mental health services management", "therapeutic solutions", "psychological support programs", 
    "mental health treatment plans", "wellness support", "psychological interventions strategies", 
    "mental health coping strategies", "therapeutic support services", "mental health research", 
    "psychosocial support tools", "emotional wellness programs", "clinical mental health services", 
    "psychological health services", "mental health resource management", "therapeutic programs", 
    "psychiatric support", "mental health support systems", "psychological resource management", 
    "mental health management tools", "wellness practices", "behavioral therapy techniques", 
    "emotional support systems", "psychosocial services management", "mental health planning", 
    "therapeutic approaches strategies", "emotional health management", "psychiatric care management", 
    "mental health support programs", "psychological interventions management", "mental health practices management", 
    "therapeutic support strategies", "psychological well-being services", "mental health support techniques", 
    "psychosocial support management", "mental health and wellness", "therapeutic health services", 
    "psychological care management", "mental health management systems", "emotional health support", 
    "mental health evaluation tools", "therapeutic services management", "psychiatric assessment tools", 
    "mental health care programs", "psychological support systems", "therapeutic wellness programs", 
    "mental health research tools", "emotional support resources", "clinical mental health management", 
    "psychological support techniques", "mental health guidance strategies", "therapeutic wellness solutions", 
    "mental health management resources", "psychosocial support systems", "psychological care tools", 
    "mental health practice strategies", "therapeutic guidance", "emotional health resources", 
    "mental health support systems management", "psychological well-being programs", 
    "clinical support services", "mental health treatment strategies", "psychological wellness solutions", 
    "mental health management techniques", "therapeutic interventions systems", "mental health wellness management", 
    "psychosocial wellness programs", "mental health support resources", "therapeutic care strategies", 
    "psychological support management", "mental health resources tools", "emotional resilience strategies", 
    "mental health service management", "psychological well-being tools", "therapeutic support management", 
    "mental health service strategies", "psychosocial care management", "mental health practice resources", 
    "therapeutic wellness management", "psychological health solutions", "mental health care strategies", 
    "psychosocial support techniques", "mental health treatment resources", "therapeutic intervention tools", 
    "mental health support services management", "psychological wellness management", "mental health support solutions", 
    "therapeutic strategies", "mental health wellness resources", "psychological care management systems", 
    "mental health management programs", "psychosocial care solutions", "therapeutic health management", 
    "mental health support practices", "psychological well-being solutions", "therapeutic support systems", 
    "mental health services management tools", "psychological care resources", "mental health guidance resources", 
    "therapeutic wellness systems", "mental health management solutions", "psychosocial support strategies", 
    "emotional wellness support", "clinical mental health strategies", "psychological wellness management", 
    "mental health treatment tools", "therapeutic solutions management", "mental health support resources management", 
    "psychological support solutions", "therapeutic care tools", "mental health practice management", 
    "psychosocial care strategies", "mental health resource management systems", "emotional support management", 
    "psychological support resources management", "mental health guidance systems", "therapeutic management solutions", 
    "mental health treatment management", "psychosocial support resources", "therapeutic solutions tools", 
    "mental health care resources management", "psychological support systems management", 
    "mental health wellness strategies", "therapeutic management tools", "mental health service resources", 
    "psychological care solutions management", "mental health management systems tools", "therapeutic health resources", 
    "psychosocial support management systems", "mental health support techniques management", 
    "psychological wellness solutions management", "mental health care management systems", "therapeutic support strategies", 
    "psychosocial support management systems tools", "mental health guidance resources management", 
    "therapeutic care management tools", "mental health management solutions systems", 
    "psychological well-being management", "mental health service solutions", "therapeutic resources management", 
    "psychosocial care management systems", "mental health support systems resources", "emotional support strategies", 
    "psychological support management systems", "mental health treatment solutions management", 
    "therapeutic wellness systems management", "psychological care management tools", "mental health wellness management systems", 
    "psychosocial support solutions management", "therapeutic support management tools", "mental health service strategies management", 
    "psychological support strategies management", "mental health resources management systems", "therapeutic solutions management systems", 
    "mental health care solutions management", "psychosocial care resources", "mental health treatment management systems", 
    "therapeutic wellness management systems", "psychological well-being resources management", 
    "mental health management resources solutions", "psychosocial support strategies management systems", 
    "mental health support systems management tools", "therapeutic management systems", "psychological care solutions resources", 
    "mental health care management solutions", "therapeutic support solutions management", 
    "psychosocial support management tools", "mental health service management resources", 
    "psychological well-being management systems", "mental health management strategies resources", 
    "therapeutic care management solutions", "psychosocial support solutions systems", "mental health support systems management resources"
  ]
  